export const GET_LINK_META_REQUEST = 'GET_LINK_META_REQUEST'
export const GET_LINK_META_SUCCESS = 'GET_LINK_META_SUCCESS'
export const GET_LINK_META_FAILURE = 'GET_LINK_META_FAILURE'

export const UPDATE_LINK_CATEGORIES = 'UPDATE_LINK_CATEGORIES'

export const ADD_LINK_REQUEST = 'ADD_LINK_REQUEST'
export const ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS'
export const ADD_LINK_FAILURE = 'ADD_LINK_FAILURE'

export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST'
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS'
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE'

export const DELETE_LINK_REQUEST = 'DELETE_LINK_REQUEST'
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS'
export const DELETE_LINK_FAILURE = 'DELETE_LINK_FAILURE'

export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'
