export const GET_LINK_META_REQUEST = 'GET_LINK_META_REQUEST'
export const GET_LINK_META_SUCCESS = 'GET_LINK_META_SUCCESS'
export const GET_LINK_META_FAILURE = 'GET_LINK_META_FAILURE'

export const UPDATE_LINK_CATEGORIES = 'UPDATE_LINK_CATEGORIES'

export const ADD_LINK_REQUEST = 'ADD_LINK_REQUEST'
export const ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS'
export const ADD_LINK_FAILURE = 'ADD_LINK_FAILURE'
